# -*- coding: utf-8 -*-
"""app.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1J-o-lxTXVGOD1Plg2mMshjwzaoD7cICG
"""

import streamlit as st
import joblib

# Load your trained model
model = joblib.load("./gradient_boosting_model.pkl")

st.title("Preeclampsia Risk Prediction App")
st.markdown("This app predicts the risk of preeclampsia based on maternal data.")

# User inputs
age = st.number_input("Age", min_value=12, max_value=50, value=28)
weight = st.number_input("Pre-pregnancy Weight (kg)", min_value=30.0, max_value=150.0, value=70.0)
parity = st.number_input("Parity", min_value=0, max_value=10, value=1)
month = st.selectbox("Month of Pregnancy", list(range(1, 10)))
systolic_bp = st.number_input("Systolic Blood Pressure (mm Hg)", min_value=80, max_value=200, value=120)
diastolic_bp = st.number_input("Diastolic Blood Pressure (mm Hg)", min_value=50, max_value=130, value=80)
proteinuria = st.number_input("Proteinuria Levels", min_value=0.0, max_value=10.0, value=0.5)

# Optional categorical inputs (encoded before prediction)
income = st.selectbox("Annual Income Level", ["Low", "Medium", "High"])
socioeconomic_status = st.selectbox("Socioeconomic Status", ["Low", "Middle", "High"])
history_hypertension = st.selectbox("History of Hypertension", ["No", "Yes"])
history_diabetes = st.selectbox("History of Diabetes", ["No", "Yes"])
history_preeclampsia = st.selectbox("History of Preeclampsia", ["No", "Yes"])

# Feature preprocessing (simplified example, should match your model's pipeline)
def preprocess_input():
    cat_map = {"Low": 0, "Medium": 1, "High": 2, "No": 0, "Yes": 1}
    return np.array([[
        age,
        weight,
        parity,
        month,
        systolic_bp,
        diastolic_bp,
        proteinuria,
        cat_map[income],
        cat_map[socioeconomic_status],
        cat_map[history_hypertension],
        cat_map[history_diabetes],
        cat_map[history_preeclampsia],
    ]])

# Prediction
if st.button("Predict Risk"):
    features = preprocess_input()
    prediction = model.predict(features)[0]
    probability = model.predict_proba(features)[0][1]

    if prediction == 1:
        st.error(f"⚠️ High Risk of Preeclampsia ({probability:.2%} probability)")
    else:
        st.success(f"✅ Low Risk of Preeclampsia ({probability:.2%} probability)")
